server:
  port: 8083

spring:
  application:
    name: claims-service

  datasource:
    url: jdbc:postgresql://localhost:5434/claimsdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
    
  cloud:
    stream:
      bindings:
        claimEvent-out-0:
          destination: claim-events

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost